# Generated by Django 4.1.2 on 2023-11-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225, null=True)),
                ('logo', models.FileField(upload_to='brand')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('deleted_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225, null=True)),
                ('libelle', models.CharField(max_length=225, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('deleted_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225, null=True)),
                ('libelle', models.CharField(max_length=225, null=True)),
                ('status', models.CharField(choices=[('canceled', 'Annulé'), ('in_progress', 'En cours'), ('paid', 'payé')], max_length=225)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lieu_livraison', models.CharField(max_length=225, null=True)),
                ('contact_livraison', models.CharField(max_length=225, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('description', models.CharField(max_length=225, null=True)),
                ('coupon_code', models.CharField(max_length=225, null=True)),
                ('percent', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('deleted_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225, null=True)),
                ('description', models.CharField(max_length=225, null=True)),
                ('prix_ht', models.FloatField(null=True)),
                ('prix_ttc', models.FloatField()),
                ('poids', models.FloatField(null=True)),
                ('stock', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.categorie')),
                ('discount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_commerce.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225, null=True)),
                ('libelle', models.CharField(max_length=225, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225, null=True)),
                ('prenom', models.CharField(max_length=225, null=True)),
                ('matricule', models.CharField(max_length=225, null=True)),
                ('login', models.CharField(max_length=225, null=True)),
                ('password', models.CharField(max_length=225, null=True)),
                ('contact', models.CharField(max_length=225, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('deleted_by', models.IntegerField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.profil')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='product_pics')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('deleted_by', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225, null=True)),
                ('libelle', models.CharField(max_length=225, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('produits', models.ManyToManyField(to='e_commerce.produit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='e_commerce.CommandeProduit', to='e_commerce.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.user'),
        ),
    ]
